### ISSUE TITLE
All stargates are destroyed on first run of this plugin in 1.14.4

### ISSUE THREAD

**Issue by runelynx** [PseudoKnight/Stargate-Bukkit#1]
Hiya,
I'm updating from 1.13.2 to 1.14.4, and at the same time changing to your version of the Stargate plugin. Unfortunately it destroys all stargates on first load. Is there a way to avoid this?

![image](https://user-images.githubusercontent.com/5877481/65826739-184c9580-e23f-11e9-8e2b-f6cf014feb4d.png)

**Comment by runelynx** [comment]
If I set your new config entry for verifyPortals to FALSE, the destruction does not happen and gates work correctly.

**Comment by PseudoKnight** [comment]
verifyPortals is highly recommended on 1.14 due to the chunk loading it causes. But this shouldn't be happening when going from 1.13 to 1.14 alone. It's also recommended to disable verifyPortals if you change your gate layouts and want to keep your old stargates. Was this the case for you?

**Comment by runelynx** [comment]
No I haven't touched the gate layouts in years :(

**Comment by PseudoKnight** [comment]
Maybe what was happening is that you were using a pre-1.13 version on 1.13.2 that was using Spigot's builtin backwards compatibility? If that's the case, when you switched to my version, which has proper 1.13+ support, you have to update your gate files to use material names, not numeric ids. If not, it'll give you error messages on startup. (eg. "Error reading plugins\Stargate\gates\nethergate.gate: portal-open is not a material")

**Comment by runelynx** [comment]
This is what my gate files look like 
![image](https://user-images.githubusercontent.com/5877481/65832897-36d28100-e27f-11e9-93a9-b87753b1dc2e.png)

**Comment by runelynx** [comment]
![image](https://user-images.githubusercontent.com/5877481/65832902-40f47f80-e27f-11e9-852d-01416c26e05a.png)

**Comment by runelynx** [comment]
I don't see materials anywhere in there, maybe that's the problem?

**Comment by PseudoKnight** [comment]
portal-open has a material, but not "X" and "-" characters. If this was the default configuration, those would be "OBSIDIAN".

**Comment by runelynx** [comment]
Oh I totally missed that
![image](https://user-images.githubusercontent.com/5877481/65832914-7a2cef80-e27f-11e9-8268-d6d39e91616e.png)

**Comment by runelynx** [comment]
can you give me a sample gate config file I can use to rework mine?

**Comment by runelynx** [comment]
oh...
I just put a material for those 2 blank =  lines?

**Comment by runelynx** [comment]
I'm half asleep sorry ;)

**Comment by PseudoKnight** [comment]
Yes.

**Comment by PseudoKnight** [comment]
But I really should make this safer for users upgrading.

**Comment by runelynx** [comment]
Perfect! Works great now. thank you!

![image](https://user-images.githubusercontent.com/5877481/65833053-9e3d0080-e280-11e9-9783-b889084e15e2.png)
