### ISSUE TITLE
Inverted horizontal view after crossing a portal

### ISSUE THREAD

**Issue by Gimlao** [PseudoKnight/Stargate-Bukkit#4]
Before crossing a portal, if you were looking to the right (or left), you will be looking to the left (or right) after crossing it.

![before-crossing](https://user-images.githubusercontent.com/841935/91289755-0cd95580-e793-11ea-93c4-ade57883b4aa.png)
![after-crossing](https://user-images.githubusercontent.com/841935/91289773-14006380-e793-11ea-94f1-522a0e186083.png)

Is it something you could fix ? <3

**Comment by PseudoKnight** [comment]
I believe this is something I already fixed locally, but didn't push it to the latest release due to time constraints. I'll do that soon.

**Comment by PseudoKnight** [comment]
To clarify, are one of these backwards gates?

**Comment by Gimlao** [comment]
Normal gates ! I actually never tried the backwards feature, by the way. x)

**Comment by PseudoKnight** [comment]
I actually hadn't fixed this yet. I was aware of it at some point and got distracted by other issues. Thanks for the report.

**Comment by Gimlao** [comment]
Thanks a lot for this fix ! I can't wait to download the next version ! <3 ( "Stargate-0.8.0.2.jar" ? )

**Comment by Gimlao** [comment]
Thanks for this fix ! <3
When will you release the next version ? :3

**Comment by PseudoKnight** [comment]
I was trying to fix another issue in the plugin first, but it's taking a lot of time consuming testing. So, I pushed a release for you.
