### ISSUE TITLE
Plugin takes money, does not create SG

### ISSUE THREAD

**Issue by Murdoxmobius** [PseudoKnight/Stargate-Bukkit#8]
Hello, 

Thank you for maintaining this, truly it is amazing. I am trying to set it up so my players can build their own portals. When this happens, they get a message saying "insufficient funds", but the SG plugin is still pulling the money, and the gate is not built. 

All other functions work fine, such as OPs building it for free. I am using Vault 1.7.3. I have looked through the code and can not find what is wrong, but based on the behavior, it seems to me like a variable is not getting passed.

**Comment by PseudoKnight** [comment]
Thanks for the report. I don't use this functionality myself, but have simply maintained it. I'll examine this part of the code, but I may need to test this interaction to determine the exact cause. What currency plugin do you use with Vault?

**Comment by PseudoKnight** [comment]
Nevermind, I think I found the issue.

**Comment by Murdoxmobius** [comment]
Thank you!
